project("HackerNews.xcodeproj")
scheme("HackerNews (iOS)")
configuration("Debug")
app_identifier("com.ejdyksen.hackernews")

devices([
  "iPhone 17 Pro Max",
  "iPad Pro 13-inch (M5)"
])

languages([
  "en-US"
])

output_directory("fastlane/screenshots")
clear_previous_screenshots(true)
override_status_bar(true)
reinstall_app(true)
skip_open_summary(true)
xcodebuild_formatter("")
